In [6]:
import torch
a = torch.tensor([1,2]).view(1,2)

In [6]:
a.shape

torch.Size([1, 2])

In [8]:
b = torch.mm(torch.tensor([1,1]).view(-1,1), a)

In [9]:
b

tensor([[1, 2],
        [1, 2]])

In [13]:
%reset
%load_ext autoreload
%autoreload 2

import sys

sys.path.append("../")
import torch
import numpy as np
import defmod as dm

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [14]:
sigma = 1
man = dm.manifold.Landmarks(2,3)
scal = dm.deformationmodules.Scaling(man, sigma)

In [22]:
scal.z().shape

torch.Size([1, 2])

In [19]:
import math
pi = math.pi
n = 3
vectors = torch.tensor([[math.cos(2*pi/n*x), math.sin(2*pi/n*x)] for x in range(n)])

In [23]:
torch.ones(1,2) * torch.ones(vectors.shape) + vectors


tensor([[2.0000, 1.0000],
        [0.5000, 1.8660],
        [0.5000, 0.1340]])

In [25]:
torch.abs(vectors)

tensor([[1.0000, 0.0000],
        [0.5000, 0.8660],
        [0.5000, 0.8660]])

In [27]:
scal.controls

tensor(1., requires_grad=True)