In [33]:
import torch
a = torch.tensor([1,2,3,4])
c = np.array([True, False, False, True])
c

array([ True, False, False,  True], dtype=bool)

In [36]:
import numpy as np
c = c.astype(int)
torch.mul(torch.tensor(c),a)

tensor([1, 0, 0, 4])

In [25]:
a[c==1]

TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.

In [20]:
[c==1]

[array([ True, False, False,  True], dtype=bool)]

In [26]:
a.shape

torch.Size([4])

In [31]:
a = torch.zeros(2,3)
a.shape

torch.Size([2, 3])

In [40]:
torch.ger(a,torch.tensor(c))

tensor([[1, 0, 0, 1],
        [2, 0, 0, 2],
        [3, 0, 0, 3],
        [4, 0, 0, 4]])

In [50]:
a = [1,2]
a

[1, 2]

In [53]:
[*a], [a]

([1, 2], [[1, 2]])